"use strict";
/**
 *  @file       actionTypes.js
 *
 *	@desc       Enum of action types.
 *
 *  @author     Colin Sullivan <colin [at] colin-sullivan.net>
 *
 *  @copyright  2017 Colin Sullivan
 *  @license    Licensed under the MIT license.
 **/
exports.__esModule = true;
exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED = exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT = exports.SEQUENCER_PROP_CHANGED = exports.SEQUENCER_PROP_CHANGE_QUEUED = exports.SEQUENCER_MIDI_OUT_CHANGED = exports.SEQUENCER_READY = exports.SEQUENCER_STOP_QUEUED = exports.SEQUENCER_STOPPED = exports.SEQUENCER_PLAYING = exports.SEQUENCER_QUEUED = void 0;
exports.SEQUENCER_QUEUED = "SC_REDUX_SEQUENCERS-SEQ_QUEUED";
exports.SEQUENCER_PLAYING = "SC_REDUX_SEQUENCERS-SEQ_PLAYING";
exports.SEQUENCER_STOPPED = "SC_REDUX_SEQUENCERS-SEQ_STOPPED";
exports.SEQUENCER_STOP_QUEUED = "SC_REDUX_SEQUENCERS-SEQ_STOP_QUEUED";
exports.SEQUENCER_READY = "SC_REDUX_SEQUENCERS-SEQ_READY";
exports.SEQUENCER_MIDI_OUT_CHANGED = "SC_REDUX_SEQUENCERS-SEQUENCER_MIDI_OUT_CHANGED";
exports.SEQUENCER_PROP_CHANGE_QUEUED = "SC_REDUX_SEQUENCERS-SEQUENCER_PROP_CHANGE_QUEUED";
exports.SEQUENCER_PROP_CHANGED = "SC_REDUX_SEQUENCERS-SEQUENCER_PROP_CHANGED";
// TODO: This should be called NEXTEVENT OR EVENT
exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT = "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_NEXTBEAT";
exports.SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED = "SUPERCOLLIDER-REDUX_SUPERCOLLIDER_EVENTSTREAMPLAYER_ENDED";
