"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SEQUENCER_PROP_CHANGED = exports.SEQUENCER_PROP_CHANGE_QUEUED = exports.SEQUENCER_MIDI_OUT_CHANGED = exports.SEQUENCER_READY = exports.SEQUENCER_STOP_QUEUED = exports.SEQUENCER_STOPPED = exports.SEQUENCER_PLAYING = exports.SEQUENCER_QUEUED = void 0;

/**
 *  @file       actionTypes.js
 *
 *	@desc       Enum of action types.
 *
 *  @author     Colin Sullivan <colin [at] colin-sullivan.net>
 *
 *  @copyright  2017 Colin Sullivan
 *  @license    Licensed under the MIT license.
 **/
var SEQUENCER_QUEUED = "AWAKENING-SEQUENCERS-SEQ_QUEUED";
exports.SEQUENCER_QUEUED = SEQUENCER_QUEUED;
var SEQUENCER_PLAYING = "AWAKENING-SEQUENCERS-SEQ_PLAYING";
exports.SEQUENCER_PLAYING = SEQUENCER_PLAYING;
var SEQUENCER_STOPPED = "AWAKENING-SEQUENCERS-SEQ_STOPPED";
exports.SEQUENCER_STOPPED = SEQUENCER_STOPPED;
var SEQUENCER_STOP_QUEUED = "AWAKENING-SEQUENCERS-SEQ_STOP_QUEUED";
exports.SEQUENCER_STOP_QUEUED = SEQUENCER_STOP_QUEUED;
var SEQUENCER_READY = "AWAKENING-SEQUENCERS-SEQ_READY";
exports.SEQUENCER_READY = SEQUENCER_READY;
var SEQUENCER_MIDI_OUT_CHANGED = "SEQUENCER_MIDI_OUT_CHANGED";
exports.SEQUENCER_MIDI_OUT_CHANGED = SEQUENCER_MIDI_OUT_CHANGED;
var SEQUENCER_PROP_CHANGE_QUEUED = "AWAKENING-SEQUENCERS-SEQUENCER_PROP_CHANGE_QUEUED";
exports.SEQUENCER_PROP_CHANGE_QUEUED = SEQUENCER_PROP_CHANGE_QUEUED;
var SEQUENCER_PROP_CHANGED = "AWAKENING-SEQUENCERS-SEQUENCER_PROP_CHANGED";
exports.SEQUENCER_PROP_CHANGED = SEQUENCER_PROP_CHANGED;